name: Publish Homey App
on:
  workflow_dispatch:

jobs:
  main:
    name: Publish Homey App
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Publish Homey App
        id: publish
        env:
          HOMEY_HEADLESS: "1"
          HOMEY_PAT: ${{ secrets.HOMEY_PAT }}
        run: |
          npm ci --ignore-scripts
          npx --yes homey@4.5.3 app publish
          echo "url=https://tools.developer.homey.app/apps/app/$(jq --raw-output .id app.json)" >> "$GITHUB_OUTPUT"

      - name: URL
        run: |
          echo "Manage your app at ${{ steps.publish.outputs.url }}." >> $GITHUB_STEP_SUMMARY
