name: Update Homey App Version
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version
        required: true
        default: patch
        options:
          - major
          - minor
          - patch
      changelog:
        type: string
        description: Changelog
        required: true

# Needed in order to push the commit and create a release
permissions:
  contents: write

jobs:
  main:
    name: Update Homey App Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Update Homey App Version
        id: update_app_version
        env:
          RELEASE_INCREMENT: ${{ inputs.version }}
          RELEASE_CHANGELOG: ${{ inputs.changelog }}
        run: |
          npx --yes homey@4.5.3 app version "$RELEASE_INCREMENT" --changelog "$RELEASE_CHANGELOG"
          echo "version=$(jq --raw-output .version app.json)" >> "$GITHUB_OUTPUT"

      - name: Sync package version
        run: npm version "${{ steps.update_app_version.outputs.version }}" --no-git-tag-version

      - name: Commit & Push
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add -A
          git commit -m "Update Homey App Version to v${{ steps.update_app_version.outputs.version }}"
          git tag "v${{ steps.update_app_version.outputs.version }}"

          git push origin HEAD --tags
          gh release create "v${{ steps.update_app_version.outputs.version }}" -t "v${{ steps.update_app_version.outputs.version }}" --notes "" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_TOKEN: ${{ github.token }}
